In [6]:
import sys
sys.path.append('..')

import pandas as pd
import sqlite3
import finance_data_pipeline as fp

conn = sqlite3.connect('../data/finance.db')
fp.init_db(conn)

In [23]:
sp500 = pd.read_csv('../data/sp500_companies.csv')
std = standardize_tickers(sp500, ticker_col='Symbol', name_col='Security', sector_col='GICS Sector')
batch_load_tickers(conn, std)

pd.read_sql("SELECT COUNT(*) AS n FROM tickers", conn)

Loaded 503 tickers.

     n
0  503

In [3]:
core_tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "JPM", "V", "JNJ"]
update_many(conn, core_tickers, interval="1d", force=True)

Fetching AAPL (1d)...
Fetching MSFT (1d)...
Fetching GOOGL (1d)...
Fetching AMZN (1d)...
Fetching NVDA (1d)...
Fetching META (1d)...
Fetching TSLA (1d)...
Fetching JPM (1d)...
Fetching V (1d)...
Fetching JNJ (1d)...

In [20]:
update_ticker_data(conn, "INTC", force=True)

Fetching INTC (1d)...

In [8]:
pd.read_sql("""
    SELECT ticker, interval, source, COUNT(*) AS bars,
           MIN(datetime) AS first_bar, MAX(datetime) AS last_bar
    FROM price_history
    GROUP BY ticker, interval, source
""", conn)

    ticker interval    source  bars   first_bar    last_bar
0        A       1d  yfinance  6724  2000-01-03  2026-09-28
1     AAPL       1d  yfinance  6724  2000-01-03  2026-09-28
2     ABBV       1d  yfinance  3455  2013-01-02  2026-09-28
3     ABNB       1d  yfinance  1455  2020-12-10  2026-09-28
4      ABT       1d  yfinance  6724  2000-01-03  2026-09-28
..     ...      ...       ...   ...         ...         ...
498    XYZ       1d  yfinance  2728  2015-11-19  2026-09-28
499    YUM       1d  yfinance  6724  2000-01-03  2026-09-28
500    ZBH       1d  yfinance  6331  2001-07-25  2026-09-28
501   ZBRA       1d  yfinance  6724  2000-01-03  2026-09-28
502    ZTS       1d  yfinance  3434  2013-02-01  2026-09-28

[503 rows x 6 columns]

In [7]:
pd.read_sql("SELECT * FROM masterlist WHERE intervals_stored IS NOT NULL", conn)

,ticker,company_name,sector,intervals_stored,sources_stored,last_updated
0,A,Agilent Technologies,Health Care,1d,yfinance,2026-09-29T21:10:20.943217
1,AAPL,Apple Inc.,Information Technology,1d,yfinance,2026-09-29T21:09:45.968226
2,ABBV,AbbVie,Health Care,1d,yfinance,2026-09-29T21:10:22.281723
3,ABNB,Airbnb,Consumer Discretionary,1d,yfinance,2026-09-29T21:10:23.122235
4,ABT,Abbott Laboratories,Health Care,1d,yfinance,2026-09-29T21:10:24.086904
...,...,...,...,...,...,...
498,XYZ,"Block, Inc.",Financials,1d,yfinance,2026-09-29T21:17:56.339249
499,YUM,Yum! Brands,Consumer Discretionary,1d,yfinance,2026-09-29T21:17:57.267387
500,ZBH,Zimmer Biomet,Health Care,1d,yfinance,2026-09-29T21:17:58.168486
501,ZBRA,Zebra Technologies,Information Technology,1d,yfinance,2026-09-29T21:17:59.031242
502,ZTS,Zoetis,Health Care,1d,yfinance,2026-09-29T21:17:59.831326

In [8]:
all_tickers = pd.read_sql("SELECT ticker FROM tickers", conn)['ticker'].tolist()
fp.update_many(conn, all_tickers, interval="1d", delay=0.5)

Fetching A (1d)...
AAPL (1d) is fresh, skipping.
ABBV (1d) is fresh, skipping.
Fetching ABNB (1d)...
ABT (1d) is fresh, skipping.
Fetching ACGL (1d)...
Fetching ACN (1d)...
ADBE (1d) is fresh, skipping.
Fetching ADI (1d)...
Fetching ADM (1d)...
Fetching ADP (1d)...
Fetching ADSK (1d)...
Fetching AEE (1d)...
AEP (1d) is fresh, skipping.
Fetching AES (1d)...
Fetching AFL (1d)...
Fetching AIG (1d)...
Fetching AIZ (1d)...
Fetching AJG (1d)...
Fetching AKAM (1d)...
Fetching ALB (1d)...
Fetching ALGN (1d)...
Fetching ALL (1d)...
Fetching ALLE (1d)...
Fetching AMAT (1d)...
Fetching AMCR (1d)...
AMD (1d) is fresh, skipping.
Fetching AME (1d)...
AMGN (1d) is fresh, skipping.
Fetching AMP (1d)...
AMT (1d) is fresh, skipping.
AMZN (1d) is fresh, skipping.
Fetching ANET (1d)...
Fetching AON (1d)...
Fetching AOS (1d)...
Fetching APA (1d)...
APD (1d) is fresh, skipping.
Fetching APH (1d)...
Fetching APO (1d)...
Fetching APP (1d)...
Fetching APTV (1d)...
Fetching ARE (1d)...
Fetching ARES (1d)...
Fetching ATO (1d)...
AVGO (1d) is fresh, skipping.
Fetching AVY (1d)...
Fetching AWK (1d)...
Fetching AXON (1d)...
Fetching AXP (1d)...
Fetching AZO (1d)...
BA (1d) is fresh, skipping.
BAC (1d) is fresh, skipping.
Fetching BALL (1d)...
Fetching BAX (1d)...
Fetching BBY (1d)...
Fetching BDX (1d)...
Fetching BE (1d)...
Fetching BEN (1d)...
Fetching BF-B (1d)...
Fetching BG (1d)...
Fetching BIIB (1d)...
BKNG (1d) is fresh, skipping.
Fetching BKR (1d)...
BLK (1d) is fresh, skipping.
Fetching BMY (1d)...
Fetching BNY (1d)...
Fetching BR (1d)...
BRK-B (1d) is fresh, skipping.
Fetching BRO (1d)...
Fetching BSX (1d)...
Fetching BX (1d)...
Fetching BXP (1d)...
C (1d) is fresh, skipping.
Fetching CAH (1d)...
Fetching CARR (1d)...
Fetching CASY (1d)...
CAT (1d) is fresh, skipping.
Fetching CB (1d)...
Fetching CBOE (1d)...
Fetching CBRE (1d)...
CCI (1d) is fresh, skipping.
Fetching CCL (1d)...
Fetching CDNS (1d)...
Fetching CDW (1d)...
CEG (1d) is fresh, skipping.
Fetching CF (1d)...
Fetching CFG (1d)...
Fetching CHD (1d)...
Fetching CHRW (1d)...
CHTR (1d) is fresh, skipping.
Fetching CI (1d)...
Fetching CIEN (1d)...
Fetching CINF (1d)...
CL (1d) is fresh, skipping.
Fetching CLX (1d)...
CMCSA (1d) is fresh, skipping.
Fetching CME (1d)...
CMG (1d) is fresh, skipping.
Fetching CMI (1d)...
Fetching CMS (1d)...
Fetching CNC (1d)...
Fetching CNP (1d)...
Fetching COF (1d)...
Fetching COHR (1d)...
Fetching COIN (1d)...
Fetching COO (1d)...
COP (1d) is fresh, skipping.
Fetching COR (1d)...
COST (1d) is fresh, skipping.
Fetching CPAY (1d)...
Fetching CPRT (1d)...
Fetching CPT (1d)...
Fetching CRH (1d)...
Fetching CRL (1d)...
CRM (1d) is fresh, skipping.
Fetching CRWD (1d)...
Fetching CSCO (1d)...
Fetching CSGP (1d)...
Fetching CSX (1d)...
Fetching CTAS (1d)...
Fetching CTSH (1d)...
Fetching CTVA (1d)...
Fetching CVNA (1d)...
Fetching CVS (1d)...
CVX (1d) is fresh, skipping.
D (1d) is fresh, skipping.
Fetching DAL (1d)...
Fetching DASH (1d)...
DD (1d) is fresh, skipping.
Fetching DDOG (1d)...
Fetching DE (1d)...
Fetching DECK (1d)...
Fetching DELL (1d)...
Fetching DG (1d)...
Fetching DGX (1d)...
Fetching DHI (1d)...
DHR (1d) is fresh, skipping.
DIS (1d) is fresh, skipping.
DLR (1d) is fresh, skipping.
Fetching DLTR (1d)...
Fetching DOC (1d)...
Fetching DOV (1d)...
DOW (1d) is fresh, skipping.
Fetching DPZ (1d)...
Fetching DRI (1d)...
Fetching DTE (1d)...
DUK (1d) is fresh, skipping.
Fetching DVA (1d)...
Fetching DVN (1d)...
Fetching DXCM (1d)...
Fetching EBAY (1d)...
Fetching ECHO (1d)...
ECL (1d) is fresh, skipping.
Fetching ED (1d)...
Fetching EFX (1d)...
Fetching EG (1d)...
Fetching EIX (1d)...
Fetching EL (1d)...
Fetching ELV (1d)...
Fetching EME (1d)...
Fetching EMR (1d)...
EOG (1d) is fresh, skipping.
EQIX (1d) is fresh, skipping.
Fetching EQT (1d)...
Fetching ERIE (1d)...
Fetching ES (1d)...
Fetching ESS (1d)...
Fetching ETN (1d)...
Fetching ETR (1d)...
Fetching EVRG (1d)...
Fetching EW (1d)...
EXC (1d) is fresh, skipping.
Fetching EXE (1d)...
Fetching EXPD (1d)...
Fetching EXPE (1d)...
Fetching EXR (1d)...
Fetching F (1d)...
Fetching FANG (1d)...
Fetching FAST (1d)...
FCX (1d) is fresh, skipping.
Fetching FDS (1d)...
FDX (1d) is fresh, skipping.
Fetching FDXF (1d)...
Fetching FE (1d)...
Fetching FERG (1d)...
Fetching FFIV (1d)...
Fetching FICO (1d)...
Fetching FIS (1d)...
Fetching FISV (1d)...
Fetching FITB (1d)...
Fetching FIX (1d)...
Fetching FLEX (1d)...
Fetching FOX (1d)...
Fetching FOXA (1d)...
Fetching FRT (1d)...
Fetching FSLR (1d)...
Fetching FTNT (1d)...
Fetching FTV (1d)...
GD (1d) is fresh, skipping.
Fetching GDDY (1d)...
GE (1d) is fresh, skipping.
Fetching GEHC (1d)...
Fetching GEN (1d)...
Fetching GEV (1d)...
Fetching GILD (1d)...
Fetching GIS (1d)...
Fetching GL (1d)...
Fetching GLW (1d)...
Fetching GM (1d)...
Fetching GNRC (1d)...
Fetching GOOG (1d)...
GOOGL (1d) is fresh, skipping.
Fetching GPC (1d)...
Fetching GPN (1d)...
Fetching GRMN (1d)...
GS (1d) is fresh, skipping.
Fetching GWW (1d)...
Fetching HAL (1d)...
Fetching HAS (1d)...
Fetching HBAN (1d)...
Fetching HCA (1d)...
HD (1d) is fresh, skipping.
Fetching HIG (1d)...
Fetching HII (1d)...
Fetching HLT (1d)...
HON (1d) is fresh, skipping.
Fetching HONA (1d)...
Fetching HOOD (1d)...
Fetching HPE (1d)...
Fetching HPQ (1d)...
Fetching HRL (1d)...
Fetching HSIC (1d)...
Fetching HST (1d)...
Fetching HSY (1d)...
Fetching HUBB (1d)...
Fetching HUM (1d)...
Fetching HWM (1d)...
Fetching IBKR (1d)...
Fetching IBM (1d)...
Fetching ICE (1d)...
Fetching IDXX (1d)...
Fetching IEX (1d)...
Fetching IFF (1d)...
Fetching ILMN (1d)...
Fetching INCY (1d)...
INTC (1d) is fresh, skipping.
Fetching INTU (1d)...
Fetching INVH (1d)...
Fetching IP (1d)...
Fetching IQV (1d)...
Fetching IR (1d)...
Fetching IRM (1d)...
Fetching ISRG (1d)...
Fetching IT (1d)...
Fetching ITW (1d)...
Fetching IVZ (1d)...
Fetching J (1d)...
Fetching JBHT (1d)...
Fetching JBL (1d)...
Fetching JCI (1d)...
Fetching JKHY (1d)...
JNJ (1d) is fresh, skipping.
JPM (1d) is fresh, skipping.
Fetching KDP (1d)...
Fetching KEY (1d)...
Fetching KEYS (1d)...
Fetching KHC (1d)...
Fetching KIM (1d)...
Fetching KKR (1d)...
Fetching KLAC (1d)...
Fetching KMB (1d)...
Fetching KMI (1d)...
KO (1d) is fresh, skipping.
Fetching KR (1d)...
Fetching KVUE (1d)...
Fetching L (1d)...
Fetching LDOS (1d)...
Fetching LEN (1d)...
Fetching LH (1d)...
Fetching LHX (1d)...
Fetching LII (1d)...
LIN (1d) is fresh, skipping.
Fetching LITE (1d)...
LLY (1d) is fresh, skipping.
LMT (1d) is fresh, skipping.
Fetching LNT (1d)...
LOW (1d) is fresh, skipping.
Fetching LRCX (1d)...
Fetching LULU (1d)...
Fetching LUV (1d)...
Fetching LVS (1d)...
Fetching LYB (1d)...
Fetching LYV (1d)...
MA (1d) is fresh, skipping.
Fetching MAA (1d)...
Fetching MAR (1d)...
Fetching MAS (1d)...
MCD (1d) is fresh, skipping.
Fetching MCHP (1d)...
Fetching MCK (1d)...
Fetching MCO (1d)...
MDLZ (1d) is fresh, skipping.
Fetching MDT (1d)...
Fetching MET (1d)...
META (1d) is fresh, skipping.
Fetching MGM (1d)...
Fetching MKC (1d)...
Fetching MLM (1d)...
Fetching MMM (1d)...
Fetching MNST (1d)...
MO (1d) is fresh, skipping.
Fetching MOS (1d)...
MPC (1d) is fresh, skipping.
Fetching MPWR (1d)...
MRK (1d) is fresh, skipping.
Fetching MRNA (1d)...
Fetching MRSH (1d)...
Fetching MRVL (1d)...
MS (1d) is fresh, skipping.
Fetching MSCI (1d)...
MSFT (1d) is fresh, skipping.
Fetching MSI (1d)...
Fetching MTB (1d)...
Fetching MTD (1d)...
Fetching MU (1d)...
Fetching NCLH (1d)...
Fetching NDAQ (1d)...
Fetching NDSN (1d)...
NEE (1d) is fresh, skipping.
NEM (1d) is fresh, skipping.
NFLX (1d) is fresh, skipping.
Fetching NI (1d)...
NKE (1d) is fresh, skipping.
Fetching NOC (1d)...
Fetching NOW (1d)...
Fetching NRG (1d)...
Fetching NSC (1d)...
Fetching NTAP (1d)...
Fetching NTRS (1d)...
NUE (1d) is fresh, skipping.
NVDA (1d) is fresh, skipping.
Fetching NVR (1d)...
Fetching NWS (1d)...
Fetching NWSA (1d)...
Fetching NXPI (1d)...
O (1d) is fresh, skipping.
Fetching ODFL (1d)...
Fetching OKE (1d)...
Fetching OMC (1d)...
Fetching ON (1d)...
ORCL (1d) is fresh, skipping.
Fetching ORLY (1d)...
Fetching OTIS (1d)...

$OTIS: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-19)

No data returned for OTIS (1d).
OXY (1d) is fresh, skipping.
Fetching P (1d)...
Fetching PANW (1d)...
Fetching PAYX (1d)...
Fetching PCAR (1d)...
PCG (1d) is fresh, skipping.
Fetching PEG (1d)...
PEP (1d) is fresh, skipping.
PFE (1d) is fresh, skipping.
Fetching PFG (1d)...
PG (1d) is fresh, skipping.
Fetching PGR (1d)...
Fetching PH (1d)...
Fetching PHM (1d)...
Fetching PKG (1d)...
PLD (1d) is fresh, skipping.
Fetching PLTR (1d)...
PM (1d) is fresh, skipping.
Fetching PNC (1d)...
Fetching PNR (1d)...
Fetching PNW (1d)...
Fetching PODD (1d)...
PPG (1d) is fresh, skipping.
Fetching PPL (1d)...
Fetching PRU (1d)...
PSA (1d) is fresh, skipping.
Fetching PSKY (1d)...

$PSKY: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-19)

No data returned for PSKY (1d).
PSX (1d) is fresh, skipping.
Fetching PTC (1d)...

$PTC: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-19)

No data returned for PTC (1d).
Fetching PWR (1d)...

$PWR: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-19)

No data returned for PWR (1d).
Fetching PYPL (1d)...
Fetching Q (1d)...
QCOM (1d) is fresh, skipping.
Fetching RCL (1d)...
Fetching RDDT (1d)...
Fetching REG (1d)...
Fetching REGN (1d)...
Fetching RF (1d)...
Fetching RJF (1d)...
Fetching RL (1d)...
Fetching RMD (1d)...
Fetching ROK (1d)...
Fetching ROL (1d)...
Fetching ROP (1d)...
Fetching ROST (1d)...
Fetching RSG (1d)...
RTX (1d) is fresh, skipping.
Fetching RVTY (1d)...
Fetching SBAC (1d)...
SBUX (1d) is fresh, skipping.
Fetching SCHW (1d)...
SHW (1d) is fresh, skipping.
Fetching SJM (1d)...
SLB (1d) is fresh, skipping.
Fetching SMCI (1d)...
Fetching SNA (1d)...
Fetching SNDK (1d)...
Fetching SNPS (1d)...
SO (1d) is fresh, skipping.
Fetching SOLV (1d)...
SPG (1d) is fresh, skipping.
Fetching SPGI (1d)...
SRE (1d) is fresh, skipping.
Fetching STE (1d)...
Fetching STLD (1d)...
Fetching STT (1d)...
Fetching STX (1d)...
Fetching STZ (1d)...
Fetching SW (1d)...
Fetching SWK (1d)...
Fetching SWKS (1d)...
Fetching SYF (1d)...
Fetching SYK (1d)...
Fetching SYY (1d)...
T (1d) is fresh, skipping.
Fetching TDG (1d)...
Fetching TDY (1d)...

$TDY: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-19)

No data returned for TDY (1d).
Fetching TECH (1d)...

$TECH: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-19)

No data returned for TECH (1d).
Fetching TEL (1d)...
Fetching TER (1d)...
Fetching TFC (1d)...
TGT (1d) is fresh, skipping.
TJX (1d) is fresh, skipping.
Fetching TKO (1d)...
TMO (1d) is fresh, skipping.
TMUS (1d) is fresh, skipping.
Fetching TPL (1d)...
Fetching TPR (1d)...
Fetching TRGP (1d)...
Fetching TRMB (1d)...
Fetching TROW (1d)...
Fetching TRV (1d)...
Fetching TSCO (1d)...
TSLA (1d) is fresh, skipping.
Fetching TSN (1d)...
Fetching TT (1d)...
Fetching TTWO (1d)...
Fetching TXN (1d)...
Fetching TXT (1d)...
Fetching TYL (1d)...
Fetching UAL (1d)...
Fetching UBER (1d)...
Fetching UDR (1d)...
Fetching UHS (1d)...
Fetching ULTA (1d)...
UNH (1d) is fresh, skipping.
UNP (1d) is fresh, skipping.
UPS (1d) is fresh, skipping.
Fetching URI (1d)...
Fetching USB (1d)...
V (1d) is fresh, skipping.
Fetching VEEV (1d)...
VICI (1d) is fresh, skipping.
VLO (1d) is fresh, skipping.
Fetching VLTO (1d)...
Fetching VMC (1d)...
Fetching VMRK (1d)...
Fetching VRSK (1d)...
Fetching VRSN (1d)...
Fetching VRT (1d)...
Fetching VRTX (1d)...

$VRTX: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-20)

No data returned for VRTX (1d).
Fetching VST (1d)...

$VST: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-20)

No data returned for VST (1d).
Fetching VTR (1d)...
Fetching VTRS (1d)...
VZ (1d) is fresh, skipping.
Fetching WAB (1d)...
Fetching WAT (1d)...

$WAT: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-20)

No data returned for WAT (1d).
WBD (1d) is fresh, skipping.
Fetching WDAY (1d)...

$WDAY: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-20)

No data returned for WDAY (1d).
Fetching WDC (1d)...
Fetching WEC (1d)...
WELL (1d) is fresh, skipping.
WFC (1d) is fresh, skipping.
Fetching WM (1d)...
Fetching WMB (1d)...
WMT (1d) is fresh, skipping.
Fetching WRB (1d)...
Fetching WSM (1d)...
Fetching WST (1d)...
Fetching WTW (1d)...

$WTW: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-20)

No data returned for WTW (1d).
Fetching WY (1d)...

$WY: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-20)

No data returned for WY (1d).
Fetching WYNN (1d)...
XEL (1d) is fresh, skipping.
XOM (1d) is fresh, skipping.
Fetching XYL (1d)...

$XYL: possibly delisted; no price data found  (1d 2000-01-01 -> 2026-10-20)

No data returned for XYL (1d).
Fetching XYZ (1d)...
Fetching YUM (1d)...
Fetching ZBH (1d)...
Fetching ZBRA (1d)...
Fetching ZTS (1d)...

In [5]:
conn.close()